
tests:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y curl
    - curl -sL https://deb.nodesource.com/setup_6.x | bash -
    - apt-get install -y nodejs python build-essential git openssh-client
    - npm install
    - npm test
  only:
    - master

deploy:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=test-messenger42 --api-key=$HEROKU_API_KEY
  only:
    - master
